# Generated by Django 2.0.9 on 2020-06-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
    ]
